runtime: python310
service: django

env_variables:
  APPENGINE_URL: django-dot-clc3-375021.ey.r.appspot.com
  WATTPILOT_TOPIC: wattpilot-config
  INVERTER_TOPIC: inverter-config

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto