# Generated by Django 4.1.5 on 2023-01-18 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('token', models.CharField(max_length=100)),
                ('site_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wattpilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('mqtt_ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('smart_charging_enabled', models.BooleanField(default=False)),
                ('inverter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.inverter')),
            ],
        ),
    ]
