# Generated by Django 4.1.5 on 2023-01-20 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inverter',
            name='ip',
        ),
    ]
