# Generated by Django 4.1.5 on 2023-01-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_inverter_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverter',
            name='wattpilot_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.DeleteModel(
            name='Wattpilot',
        ),
    ]
