# Generated by Django 4.1.5 on 2023-01-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_inverter_wattpilot_id_delete_wattpilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverter',
            name='smart_charging_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
